#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';
if (class_exists('Dotenv\Dotenv')) {
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->safeLoad();
}

defined('YII_DEBUG') or define('YII_DEBUG', isset($_ENV['YII_DEBUG']) ? filter_var($_ENV['YII_DEBUG'], FILTER_VALIDATE_BOOLEAN) : true);
defined('YII_ENV') or define('YII_ENV', isset($_ENV['YII_ENV']) ? strtolower($_ENV['YII_ENV']) : 'dev');

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
